### PR TITLE
CWL for preprocessing, alnspread, alngather

### PR DESCRIPTION
**Pull request by inutano**
CWL definition to wrap `dncalign`. This requires to build docker image with the tag name `naturalis/covid19-phylogeny` before running this CWL. 

It is not yet tested because I don't have cipres key, so I'd recommend to merge this after I've confirmed with the app key.

### CODE REVIEW

**Comment by rvosa** [comment]
Thanks very much! There is basically one more step to do, i.e. inferring the tree, but I will do that myself using the code you have now as a template. 

Were you still planning to run a test on your end? Otherwise I am inclined to just merge the PR.

**Comment by inutano** [comment]
Still running a test on my machine, will let you know when it's done and ready to merge

**Comment by rvosa** [comment]
Hi Tazro (@inutano), I am going to close this PR because the underlying interfaces have changed so much that it would be a big job to redesign and resolve conflicts from the current situation.

Instead, I will use the code you wrote here as examples for one or two CWL wrappers that will orchestrate the invocation of `cipresrun` under different parameters. That way, I will have addressed issue #5.

Thank you very much for all your help and for an amazing hackathon! I hope you are doing well!

**Comment by inutano** [comment]
Thanks @rvosa it's totally okay ;) Let me know if I could help you to create the new CWL definitions, since sometimes you need to do tricky thing when you package a tool in CWL (mainly due to the tool behaviour).

As mentioned in the vBH slack team, @tetron and I are concerning about the reproducibility of the process in CIPRES server. Let us know if we could help to make the process portable and run it in the Arvados server, which has fairly a large computation resource.

**Pull request closed without merging**
